### ISSUE TITLE
Channel ID not found

### ISSUE THREAD

**Issue by Marjaperse** [polywock/youtubeEye#2]
When searching for popular videos by clicking the box next to the channel name, "Channel ID not found" window pops up.

Comments can be searched fine.

**Comment by polywock** [comment]
Hello. Youtube changed the way they link youtube channels. It was a pain to figure out, but I think I managed to fix it. The update is now available for Chrome/Firefox, but the Edge store version might take a week or so.

Since youtube removed dislikes, I also changed the like ratio to an engagement ratio (likes relative to views). 

Let me know if the issue is fixed for you.

**Comment by Marjaperse** [comment]
Nice, it works fine now. Good work!
